/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTestingRouteImport } from './routes/dashboard/testing'
import { Route as DashboardSprintBacklogRouteImport } from './routes/dashboard/sprintBacklog'
import { Route as DashboardBacklogRouteImport } from './routes/dashboard/backlog'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTestingRoute = DashboardTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSprintBacklogRoute = DashboardSprintBacklogRouteImport.update({
  id: '/sprintBacklog',
  path: '/sprintBacklog',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBacklogRoute = DashboardBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard/backlog': typeof DashboardBacklogRoute
  '/dashboard/sprintBacklog': typeof DashboardSprintBacklogRoute
  '/dashboard/testing': typeof DashboardTestingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard/backlog': typeof DashboardBacklogRoute
  '/dashboard/sprintBacklog': typeof DashboardSprintBacklogRoute
  '/dashboard/testing': typeof DashboardTestingRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/dashboard/backlog': typeof DashboardBacklogRoute
  '/dashboard/sprintBacklog': typeof DashboardSprintBacklogRoute
  '/dashboard/testing': typeof DashboardTestingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard/backlog'
    | '/dashboard/sprintBacklog'
    | '/dashboard/testing'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard/backlog'
    | '/dashboard/sprintBacklog'
    | '/dashboard/testing'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/dashboard/backlog'
    | '/dashboard/sprintBacklog'
    | '/dashboard/testing'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/testing': {
      id: '/dashboard/testing'
      path: '/testing'
      fullPath: '/dashboard/testing'
      preLoaderRoute: typeof DashboardTestingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sprintBacklog': {
      id: '/dashboard/sprintBacklog'
      path: '/sprintBacklog'
      fullPath: '/dashboard/sprintBacklog'
      preLoaderRoute: typeof DashboardSprintBacklogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/backlog': {
      id: '/dashboard/backlog'
      path: '/backlog'
      fullPath: '/dashboard/backlog'
      preLoaderRoute: typeof DashboardBacklogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardBacklogRoute: typeof DashboardBacklogRoute
  DashboardSprintBacklogRoute: typeof DashboardSprintBacklogRoute
  DashboardTestingRoute: typeof DashboardTestingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBacklogRoute: DashboardBacklogRoute,
  DashboardSprintBacklogRoute: DashboardSprintBacklogRoute,
  DashboardTestingRoute: DashboardTestingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
