/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardSkeletonRouteImport } from './routes/dashboardSkeleton'
import { Route as DashBoardRouteImport } from './routes/dashBoard'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const DashboardSkeletonRoute = DashboardSkeletonRouteImport.update({
  id: '/dashboardSkeleton',
  path: '/dashboardSkeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const DashBoardRoute = DashBoardRouteImport.update({
  id: '/dashBoard',
  path: '/dashBoard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/dashBoard': typeof DashBoardRoute
  '/dashboardSkeleton': typeof DashboardSkeletonRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/dashBoard': typeof DashBoardRoute
  '/dashboardSkeleton': typeof DashboardSkeletonRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/dashBoard': typeof DashBoardRoute
  '/dashboardSkeleton': typeof DashboardSkeletonRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/counter'
    | '/dashBoard'
    | '/dashboardSkeleton'
    | '/login'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/counter'
    | '/dashBoard'
    | '/dashboardSkeleton'
    | '/login'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/counter'
    | '/dashBoard'
    | '/dashboardSkeleton'
    | '/(auth)/login'
    | '/(auth)/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CounterRoute: typeof CounterRoute
  DashBoardRoute: typeof DashBoardRoute
  DashboardSkeletonRoute: typeof DashboardSkeletonRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboardSkeleton': {
      id: '/dashboardSkeleton'
      path: '/dashboardSkeleton'
      fullPath: '/dashboardSkeleton'
      preLoaderRoute: typeof DashboardSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashBoard': {
      id: '/dashBoard'
      path: '/dashBoard'
      fullPath: '/dashBoard'
      preLoaderRoute: typeof DashBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CounterRoute: CounterRoute,
  DashBoardRoute: DashBoardRoute,
  DashboardSkeletonRoute: DashboardSkeletonRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
